apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2021-03-12T00:29:09Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:roleRef:
        f:apiGroup: {}
        f:kind: {}
        f:name: {}
      f:subjects: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-12T00:29:09Z"
  name: cluster-system-serviceaccount-appgate-test-1-default
  resourceVersion: "34008"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/cluster-system-serviceaccount-appgate-test-1-default
  uid: 40b06464-839e-49f0-8bea-e0e445c51791
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:appgate-test-1:default
