apiVersion: v1
kind: Secret
metadata:
  name: appgate-operator-creds
  namespace: appgate-test-1
type: Opaque
data:
  appgate-operator-user: YWRtaW4=
  appgate-operator-password: MGhSRVglazJ5N2wzdlklSQ==
