apiVersion: beta.appgate.com/v1
kind: LocalUser
metadata:
  name: blambert
  namespace: appgate-test-1
spec:
  appgate_metadata:
    passwordFields:
    - password
    uuid: b8d6d431-7137-47bc-8933-076ebbf2b597
  email: blambert@applied-insight.com
  failedLoginAttempts: 0
  firstName: Bob
  lastName: Lambert
  password: 'Galena'
  name: blambert
---
apiVersion: beta.appgate.com/v1
kind: LocalUser
metadata:
  name: jlambert
  namespace: appgate-test-1
spec:
  appgate_metadata:
    passwordFields:
    - password 
    uuid: b8d6d431-7137-47bc-8933-076ebbf2b597
  email: jlambert@applied-insight.com
  failedLoginAttempts: 0
  firstName: Joshua
  lastName: Lambert
  password: 'Galena'
  name: jlambert
---
apiVersion: beta.appgate.com/v1
kind: Entitlement
metadata:
  name: admin
  namespace: appgate-test-1
spec:
  actions:
  - action: allow
    hosts:
    - 10.0.0.0/8
    ports:
    - 1-62536
    subtype: tcp_up
    monitor: 
      properties:
        enabled: false
  appgate_metadata:
    uuid: bceb265a-5b5b-4686-82af-ae0a9956715b
  conditions:
  - Always
  name: admin
  site: Default Site
---
apiVersion: beta.appgate.com/v1
kind: Policy
metadata:
  name: builtin-administrator-policy
  namespace: appgate-test-1
spec:
  administrativeRoles:
  - System Administration
  appgate_metadata:
    uuid: 172143a0-7ed4-11e4-b4a9-0800200c9a66
  expression: "//Generated by criteria builder, Operator: and\n         var result\
    \ = false;\n         if/*claims.user.ag.identityProviderId*/(claims.user.ag &&\
    \ claims.user.ag.identityProviderId === \"b5ea7cf0-6e75-11e4-9803-0800200c9a66\"\
    )/*end claims.user.ag.identityProviderId*/ { result = true; } else { return false;\
    \ }\n         if/*claims.user.username*/(claims.user.username === \"admin\")/*end\
    \ claims.user.username*/ { result = true; } else { return false; }\n         return\
    \ result;"
  name: Builtin Administrator Policy
  notes: Policy for built-in admin user.
  tags:
  - builtin
---
apiVersion: beta.appgate.com/v1
kind: Policy
metadata:
  name: admin
spec:
  administrativeRoles:
  - System Administration
  - Api Access
  appgate_metadata:
    uuid: 20537a0c-02c2-4d2f-9719-361324d0146b
  entitlements:
  - admin
  expression: '//Generated by criteria builder, Operator: and

    var result = false;

    if/*claims.user.username*/(claims.user.username === "jlambert")/*end claims.user.username*/
    { result = true; } else { return false; }

    return result;'
  name: admin
---
apiVersion: beta.appgate.com/v1
kind: ClientConnection
metadata:
  name: clientconnection
  namespace: appgate-test-1
spec:
  profiles:
  - identityProviderName: local
    name: admin
    spaKeyName: '12345'
