apiVersion: beta.appgate.com/v1
kind: LocalUser
metadata:
  name: jlambert
  namespace: appgate-test-1
spec:
  appgate_metadata:
    passwordFields:
    - password: R2FsZW5h
    uuid: b8d6d431-7137-47bc-8933-076ebbf2b597
  email: jlambert@applied-insight.com
  failedLoginAttempts: 0
  firstName: Joshua
  lastName: Lambert
  name: jlambert
