apiVersion: beta.appgate.com/v1
kind: LocalUser
metadata:
  name: jlambert
spec:
  appgate_metadata:
    passwordFields:
    - password
    uuid: b8d6d431-7137-47bc-8933-076ebbf2b597
  email: jlambert@applied-insight.com
  failedLoginAttempts: 0
  firstName: Joshua
  lastName: Lambert
  name: jlambert
---
apiVersion: beta.appgate.com/v1
kind: LocalUser
metadata:
  name: admin
spec:
  appgate_metadata:
    passwordFields:
    - password
    uuid: 5e360c9d-8756-41b4-9597-601712881a5c
  email: admin@email.com
  failedLoginAttempts: 0
  firstName: Builtin
  lastName: Administrator
  name: admin
  notes: Built-in administrator user.
  tags:
  - builtin
