apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-namespace.yaml
- 01-config.yaml
- 01-role.yaml
- 01-ClusterRoleBinding.yaml
- 01-secrets.yaml
- 00-appgate-test-crd-v13.yaml
- 02-appgate-operator.yaml
- LocalUser.yaml
